main: su.nightexpress.coinsengine.CoinsEnginePlugin
version: '${project.version}'
name: CoinsEngine
author: NightExpress
desciption: Unlimited virtual currencies with Vault Economy support!
depend:
  - nightcore
  - SmashEngine
softdepend:
  - Vault
  - PlaceholderAPI
  - PlayerPoints
  - DeluxeCoinflip
load: STARTUP
api-version: 1.18